services:
    db:
        image: mysql:8.0
        container_name: crud-me_db
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        volumes:
            - db_data_dev:/var/lib/mysql

    web:
        build:
            context: .
            dockerfile: .dockerfile
        container_name: crud-me_web
        environment:
            DB_HOST: db
            DB_CONNECTION: mysql
        volumes:
            - ./:/var/www/html
            - ./vhost.conf:/etc/apache2/sites-available/000-default.conf
        ports:
            - "8080:80"
        depends_on:
            - db

volumes:
    db_data_dev:
